# render.yaml
services:
  - type: web
    name: number-ninja-api-east
    env: python
    rootDir: backend
    buildCommand: pip install -requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://number_ninja_user:1pBGBzlcJamyVJV6Up7UBMI8OTiWxt8a@dpg-cu46a15ds78s739ou3s0-a.virginia-postgres.render.com/number_ninja
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: number_ninja_db
    databaseName: number_ninja
    user: number_ninja_user
    plan: free