# render.yaml
services:
  - type: web
    name: number-ninja-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: number_ninja_db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0

databases:
  - name: number_ninja_db
    databaseName: number_ninja
    user: number_ninja_user