# render.yaml
services:
  - type: web
    name: number-ninja-api
    env: python
    rootDir: backend  # Add this line
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: number_ninja_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.8

databases:
  - name: number_ninja_db
    databaseName: number_ninja
    user: number_ninja_user
    plan: free