"""Add difficulty levels to Score model

Revision ID: 4e3f07ec899b
Revises: 3d5e0e09d3c1
Create Date: 2025-03-09 17:17:33.904892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3f07ec899b'
down_revision = '3d5e0e09d3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('max_number')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
