"""Add premium_themes field to User model

Revision ID: 6448e61964c0
Revises: 4e3f07ec899b
Create Date: 2025-03-16 03:19:37.875695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6448e61964c0'
down_revision = '4e3f07ec899b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium_themes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('premium_themes')

    # ### end Alembic commands ###
