"""Add Google Auth to User model

Revision ID: 898d6a514cd3
Revises: 6448e61964c0
Create Date: 2025-03-20 08:01:25.807154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898d6a514cd3'
down_revision = '6448e61964c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
